{
 "title": "3FS Cluster",
 "description": "The Grafana monitoring dashboard for the cluster granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:44:32.010Z", "to": "2025-05-08T11:50:15.830Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'META')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP)) AND \n      (\"metricName\" = 'MgmtdService.NodeStatusCount') AND \n      (\"instance\" = 'META') AND \n      (\"tag\" = 'HEARTBEAT_CONNECTED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTING')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'STORAGE')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTING')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Mgmtd Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTING')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_FAILED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'DISABLED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "R/W Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.read.bytes')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    },
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.bytes')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    }
   ]
  },
  {
   "title": "Storage Num",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT host, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY host\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT pod, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY pod\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT concat(host, '-', pod, '-', instance) AS hpi, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY hpi\n)"
    }
   ]
  },
  {
   "title": "Storage Target Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 0) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 1) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 2) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 4) \n    GROUP BY instance\n)"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.capacity')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    },
    {
     "rawSql": "SELECT (a.total_val - b.total_val) AS \" \"\nFROM \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.capacity')\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP DESC\n        LIMIT 1, 1\n    ) a\nJOIN \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.free')\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP DESC\n        LIMIT 1, 1\n    ) b\nON (a.TIMESTAMP = b.TIMESTAMP)\nORDER BY a.TIMESTAMP ASC"
    },
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.free')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    }
   ]
  },
  { "title": "Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"read\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.read.bytes')\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"write\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.bytes')\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Read Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"read\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_read.total')\nGROUP BY TIMESTAMP, instance"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"write\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.total')\nGROUP BY TIMESTAMP, instance"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_read.succ_latency')\nGROUP BY TIMESTAMP, host, instance\n"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.succ_latency')\nGROUP BY TIMESTAMP, host, instance"
    }
   ]
  },
  { "title": "OP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Fuse OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.op')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Meta Client OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Meta Server OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "FoundationDB OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, substr(metricName, 17), SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'fdb_total_count_'))\nGROUP BY TIMESTAMP, metricName\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Mgmtd Client OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Mgmtd Service OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  }
 ]
}