{
 "title": "3FS FoundationDB",
 "description": "The Grafana monitoring dashboard for the foundationdb granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:39:14.668Z", "to": "2025-05-08T11:54:46.912Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND startsWith(\"metricName\", 'fdb_total_count_')\nORDER BY TIMESTAMP ASC"
   }
  ]
 },
 "panels": [
  { "title": "Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"get\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_get')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"set\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_set')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"commit\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_commit')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "GetRange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"get_range\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_get_range')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "SetVersionstampedValue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"set_versionstamped_value\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_set_versionstamped_value')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "SnapshotGetRange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"snapshot_get_range\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_snapshot_get_range')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "SnapshotGet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"snapshot_get\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_snapshot_get')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "AddReadConflict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"add_read_conflict\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_add_read_conflict')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Clear",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \"clear\"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_total_count_clear')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_latency_get')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_latency_commit')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "GetRange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_latency_get_range')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "SnapshotGetRange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_latency_snapshot_get_range')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  },
  {
   "title": "SnapshotGet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fdb_latency_snapshot_get')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nGROUP BY TIMESTAMP"
    }
   ]
  }
 ]
}