{
 "title": "3FS Fuse",
 "description": "The Grafana monitoring dashboard for the fuse granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:44:32.010Z", "to": "2025-05-08T11:50:15.830Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP)) AND (\"metricName\" = 'fuse.op')\nORDER BY TIMESTAMP ASC"
   },
   {
    "name": "uid",
    "label": "UID",
    "query": "SELECT DISTINCT uid\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP)) AND (\"metricName\" = 'fuse.op')\nORDER BY TIMESTAMP ASC"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.op')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.bw')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Dirty INodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.dirty_inodes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.write.size')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov IO Size Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.io_size.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.write.latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Overall Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.overall.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Prepare Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.prepare.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Submit Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.submit.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Complete Write Latency",
   "type": "timeseries",
   "description": "Including the time of submit.write ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, AVG(mean) AS \"mean\", AVG(p50) AS \"p50\", AVG(p90) AS \"p90\", AVG(p95) AS \"p95\", AVG(p99) AS \"p99\"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.complete.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nGROUP BY TIMESTAMP, host, uid, mount_name\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, val AS \" \", concat(host, ': uid', uid , ': ', instance)\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.op')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Dirty INodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.dirty_inodes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Fuse Piov BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid , ': ', mount_name), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.bw')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Usrbio Piov BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid , ': ', mount_name), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'usrbio.piov.bw')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.write.size')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.write.latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Overall Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.overall.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov IO Size Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.io_size.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Submit Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.submit.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Prepare Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.prepare.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Piov Complete Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', mount_name), mean, p50, p90, p95, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'fuse.piov.complete.write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  }
 ]
}