{
 "title": "3FS Meta",
 "description": "The Grafana monitoring dashboard for the meta granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:44:32.010Z", "to": "2025-05-08T11:50:15.830Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'meta_client.op_') OR startsWith(\"metricName\", 'meta_server.op_'))\nORDER BY TIMESTAMP ASC"
   },
   {
    "name": "uid",
    "label": "UID",
    "query": "SELECT DISTINCT uid\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND uid IS NOT NULL\n      AND uid != ''\n      AND (startsWith(\"metricName\", 'meta_client.op') OR startsWith(\"metricName\", 'meta_server.op'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'META')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP)) AND \n      (\"metricName\" = 'MgmtdService.NodeStatusCount') AND \n      (\"instance\" = 'META') AND \n      (\"tag\" = 'HEARTBEAT_CONNECTED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTING')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    }
   ]
  },
  { "title": "MetaClient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "MetaClient OP Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient OP Code",
   "type": "timeseries",
   "description": "0: success",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': code', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_code')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Prefer Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.prefer_server')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient OP Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_running')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient OP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.server_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Get Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.get_server')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient OP Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.op_retry')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.network_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Inflight Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.inflight_time')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Truncate Iters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.truncate_iters')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Truncate Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.truncate_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaClient Remove Chunks Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_client.remove_chunks_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "MetaServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "MetaServer OP Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer OP Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': uid', uid, ': ', instance, 'code', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_code')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${uid:csv}', '*'), (uid IN (${uid})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Batch OP Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.batch_op_size')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer ACL Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.aclcache_hit')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Stat File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.stat_file')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Stat Dir",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.stat_dir')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Remove Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.remove_chunks')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer ACL Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.aclcache_miss')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer GC Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.gc_success')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Open Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.open_write')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer OP Idempotent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_idempotent')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer GC Enqueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.gc_enqueue')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Remove Chunks Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.remove_chunks_size')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer GC Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.gc_chunks')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Path Components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.path_components')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer GC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.gc_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer OP Retry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_retry')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Query Last Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.query_last_chunk')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Path Components By User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': user', uid), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.path_components_by_user')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer OP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ' : ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.op_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer Remove Chunks Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server.remove_chunks_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MetaServer List Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'meta_server:list_entries')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  }
 ]
}