{
 "title": "3FS Mgmtd",
 "description": "The Grafana monitoring dashboard for the mgmtd granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:44:32.010Z", "to": "2025-05-08T11:50:15.830Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'MgmtdClient.op') OR startsWith(\"metricName\", 'MgmtdService.op'))\nORDER BY TIMESTAMP ASC"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mgmtd Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_CONNECTING')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'HEARTBEAT_FAILED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (\"instance\" = 'MGMTD')\n      AND (\"tag\" = 'DISABLED')\nORDER BY TIMESTAMP DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mgmtd Client OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Mgmtd Service OP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.total')\nGROUP BY TIMESTAMP, instance\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "MgmtdClient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "MgmtdClient OP Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdClient OP SuccLat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.succ_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdClient OP Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.current')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdClient OP Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.fails')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdClient OP FailLat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdClient.op.fail_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "MgmtdServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "MgmtdService OP Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService OP Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.current')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService OP Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.fails')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService OP Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.succ_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService OP Fail Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.op.fail_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Writer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.WriterLatency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService WriterUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, val AS \" \", concat(host, ': ', instance)\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.WriterUsage')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Routing Info Version ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.RoutingInfoVersion')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Chain Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ChainCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Chain Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ChainCountByReplica')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Chain Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance, ': ', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ChainStatus')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Node Status",
   "type": "timeseries",
   "description": "1: HEARTBEAT_CONNECTED <br />\n2: HEARTBEAT_CONNECTING <br />\n3: HEARTBEAT_FAILED <br />\n4: DISABLED",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatus')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Node Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance, ': ', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.NodeStatusCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Release Version Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance, ': ', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ReleaseVersionCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Target Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.TargetCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Target Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ',  instance, ': ', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.TargetStatusCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Target Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.TargetCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Lease Lasting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.LeaseLasting')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Config Version ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ConfigVersions')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Config Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance, ': ', tag), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.ConfigStatusCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Background Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.bg.current')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Background Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.bg.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdServic BG Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.bg.succ_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "MgmtdService Orphan Target Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, instance, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'MgmtdService.OrphanTargetCount')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  }
 ]
}