{
 "title": "3FS Storage",
 "description": "The Grafana monitoring dashboard for the storage granularity of the 3FS (Fire-Flyer File System).",
 "time": { "from": "2025-05-08T11:44:32.010Z", "to": "2025-05-08T11:50:15.830Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT DISTINCT host\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.capacity')\nORDER BY TIMESTAMP ASC"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SELECT DISTINCT instance\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.capacity')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "SELECT DISTINCT instance\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.forward.write_bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Num",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT host, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY host\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT pod, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY pod\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT concat(host, '-', pod, '-', instance) AS hpi, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.disk_info.available')\n    GROUP BY hpi\n)"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.capacity')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    },
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.free')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    },
    {
     "rawSql": "SELECT (a.total_val - b.total_val) AS \" \"\nFROM \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.capacity')\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP DESC\n        LIMIT 1, 1\n    ) a\nJOIN \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.free')\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP DESC\n        LIMIT 1, 1\n    ) b\nON (a.TIMESTAMP = b.TIMESTAMP)\nORDER BY a.TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "R/W Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.read.bytes')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    },
    {
     "rawSql": "SELECT SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.bytes')\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP DESC\nLIMIT 1, 1"
    }
   ]
  },
  {
   "title": "Storage Target Status",
   "type": "stat",
   "description": "HB is a shot of HEARTBEAT",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 0) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 1) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 2) \n    GROUP BY instance\n)"
    },
    {
     "rawSql": "SELECT count() AS \" \"\nFROM (\n    SELECT instance, argMax(val, TIMESTAMP) AS latest_val\n    FROM \"3fs\".\"counters\"\n    WHERE ($__timeFilter(TIMESTAMP))\n          AND (\"metricName\" = 'storage.target_state')\n          AND (\"val\" = 4) \n    GROUP BY instance\n)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.read.bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Read Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_read.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_read.succ_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.succ_latency')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Bytes (Chain Head)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Update Bytes (Not Chain Head)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_update.bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "RDMA Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.rdma_write.bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Write Count (Chain Head)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': user', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_write.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Update Count (Not Chain Head)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': user', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_update.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "RDMA Write Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.rdma_write.count')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Check Disk Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.check_disk.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Disk Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.capacity')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    },
    {
     "rawSql": "SELECT TIMESTAMP, SUM(val) AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.disk_info.available')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nGROUP BY TIMESTAMP\nORDER BY TIMESTAMP ASC"
    },
    {
     "rawSql": "SELECT TIMESTAMP, (a.total_val - b.total_val) AS \" \"\nFROM \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.capacity')\n              AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n              AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP ASC\n    ) a\nJOIN \n    (\n        SELECT TIMESTAMP, SUM(val) AS \"total_val\"\n        FROM \"3fs\".\"counters\"\n        WHERE ($__timeFilter(TIMESTAMP))\n              AND (\"metricName\" = 'storage.disk_info.free')\n              AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n              AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\n        GROUP BY TIMESTAMP\n        ORDER BY TIMESTAMP ASC\n    ) b\nON (a.TIMESTAMP = b.TIMESTAMP)\nORDER BY a.TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Forward Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.forward.write_bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${target:csv}', '*'), (instance IN (${target})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Target State",
   "type": "timeseries",
   "description": "0: INVALID <br />\n1: UPTODATE <br />\n2: ONLINE <br />\n4: OFFLINE",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, val AS \" \", concat(host, ': ', instance)\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.target_state')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${target:csv}', '*'), (instance IN (${target})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Sys CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.sys.cpu_cores')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "StorageClient", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Storage Client Data Payload Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.data_payload_bytes')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Processed Chunks Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_processed_chunks')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Completed OP Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_completed_ops')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Data Payload Bytes (Per User)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', uid, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.data_payload_bytes_per_user')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Num Processed Chunks (Per User)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', uid, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_processed_chunks_per_user')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Completed OP Num (Per User)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', uid, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_completed_ops_per_user')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "StorageClient Update Channel Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_update_channels.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client OPs (Per User Call)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.ops_per_user_call')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Requests (Per User Call)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.requests_per_user_call')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Accessed Servers (Per User Call)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.accessed_servers_per_user_call')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Bytes (Per User Call)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.bytes_per_user_call')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Requests (Per Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.requests_per_server')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client OPs (Per Request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.ops_per_request')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Bytes (Per Request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.bytes_per_request')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Overall Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.overall_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Waiting Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.waiting_time')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.request_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Inflight Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.inflight_time')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.server_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.network_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Concurrent User Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.concurrent_user_calls')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Num Pending OPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_pending_ops')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.inflight_requests')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Request BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.request_bw')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client User Call BW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.user_call_bw')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "StorageClient Num Update Channels Inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.num_update_channels.inuse')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client Bytes (Per Operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.bytes_per_operation')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "StorageClient IO Buf Reg Success OPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.iobuf_reg.success_ops')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client IO Buf Reg Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.iobuf_reg.size')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Client IO Buf Reg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage_client.iobuf_reg.latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Storage Wait", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Storage Wait Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(substring(metricName, 14), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.wait_aio.total', 'storage.wait_sem.total', 'storage.wait_batch.total', 'storage.wait_post.total', 'storage.wait_aio_and_post.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(substring(metricName, 14), '.current', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.wait_aio.current', 'storage.wait_sem.current', 'storage.wait_batch.current', 'storage.wait_post.current', 'storage.wait_aio_and_post.current'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Channel Lock Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_channel_lock.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Chunk Lock Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_chunk_lock.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Write Wait Sem Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.write_wait_sem.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Post Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_post.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Sem Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_sem.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Chunk Lock Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_chunk_lock.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait AIO And Post Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_aio_and_post.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Write Wait Post Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.write_wait_post.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Channel Lock Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_channel_lock.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait AIO Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_aio.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Batch Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_batch.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Wait Channel Lock Fail Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.wait_channel_lock.fail_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Storage Chunk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 182 } },
  {
   "title": "Storage Chunk Remove Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_remove.times')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Allocate Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.allocate_times')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Allocate Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.allocate_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Checksum Combine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.checksum_combine')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Pwrite Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.pwrite_times')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Pwrite Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.pwrite_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine New",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.new')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Position RC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.position_rc')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine Position Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.position_count')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Write Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_write.times')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine SafeWriteDirectAppend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.safe_write_direct_append')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Chunk Engine SafeWriteTruncateExtend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.chunk_engine.safe_write_truncate_extend')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\n      AND (if(notEquals('${disk:csv}', '*'), (instance IN (${disk})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Storage Do", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 215 } },
  {
   "title": "Storage Do Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(substring(metricName, 12), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'storage.do_'))\n      AND (endsWith(\"metricName\", '.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Do Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(substring(metricName, 12), '.succ_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'storage.do_'))\n      AND (endsWith(\"metricName\", '.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Do Remove Num Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.do_remove.num_chunks')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 } },
  {
   "title": "Storage IO Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.io_', ''), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.io_collect.total', 'storage.io_submit.total', 'storage.io_getevents.total'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage IO Submit Loop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.io_submit.loop')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage IO Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.io_', ''), '.size', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.io_getevents.size', 'storage.io_submit.size'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Engine Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(substring(metricName, 16), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'storage.engine_'))\n      AND (endsWith(\"metricName\", '.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Reliable Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.reliable_', ''), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.reliable_update.total', 'storage.reliable_forward.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Read Prepare Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.read_prepare_', ''), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.read_prepare_buffer.total', 'storage.read_prepare_target.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Engine Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.engine_', ''), '.succ_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (startsWith(\"metricName\", 'storage.engine_'))\n      AND (endsWith(\"metricName\", '.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Reliable Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.reliable_', ''), '.succ_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.reliable_forward.succ_latency', 'storage.reliable_update.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Read Prepare Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.read_prepare_', ''), '.succ_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.read_prepare_target.succ_latency', 'storage.read_prepare_buffer.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Enqueue Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio_enqueue.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio.inflight')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Align Total Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio_align.total_length')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Enqueue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio_enqueue.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Batch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio.batch_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage AIO Running Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.aio_running_threads.count')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.io_', ''), '.succ_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.io_submit.succ_latency', 'storage.io_collect.succ_latency', 'storage.io_getevents.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Req Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.req_', ''), '.succ_latency', ''), ': disk', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.req_write.succ_latency', 'storage.req_read.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Check Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.check_disk.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Read Avg Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND ( \"metricName\" = 'storage.read.avg_bytes' )\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Read Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.read.queue_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Batch Read In Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.batch_read_in_queue.latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Req Remove Chunks Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_remove_chunks.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Trace Log Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance, ': ', replaceAll(replaceAll(metricName, 'trace_log.', ''), '_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('trace_log.create_latency', 'trace_log.append_latency', 'trace_log.flush_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Req Read Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.req_read.size')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Update Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.update_', ''), '.total', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.update_routing.total', 'storage.update_remote.total'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Update Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.update.queue_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Default Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.default.queue_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Remove Range Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.remove_range.total')\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Write Wait Sem Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', instance), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.write_wait_sem.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Reliable Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(metricName, 'storage.reliable_update.', '')), val AS \" \"\nFROM \"3fs\".\"counters\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.reliable_update.cached', 'storage.reliable_update.waited'))\n      AND (if(notEquals('${host:csv}', '*'), (host IN (${host})), 1))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Forward Write Dist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ' : ', instance), mean, p99\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.forward.write_dist')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Req Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': disk', instance, ': ', replaceAll(replaceAll(metricName, 'storage.req_', ''), '_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.req_update.succ_latency', 'storage.req_update.fail_latency', 'storage.req_remove_chunks.succ_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Update Routing Succ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.update_routing.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Update Remote Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, concat(host, ': ', replaceAll(replaceAll(metricName, 'storage.update_remote.', ''), '_latency', '')), mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" IN ('storage.update_remote.succ_latency', 'storage.update_remote.fail_latency'))\nORDER BY TIMESTAMP ASC"
    }
   ]
  },
  {
   "title": "Storage Remove Range Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMP, host, mean AS \" \"\nFROM \"3fs\".\"distributions\"\nWHERE ($__timeFilter(TIMESTAMP))\n      AND (\"metricName\" = 'storage.remove_range.succ_latency')\nORDER BY TIMESTAMP ASC"
    }
   ]
  }
 ]
}